version: "3.9"

services:
  kafka:
    image: bitnami/kafka:$KAFKA_VERSION
    container_name: $NAME
    restart: unless-stopped
    ports:
      - $KAFKA_PORT:9092
    volumes:
      - kafka_data:/bitnami
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:$ZK_VERSION
    container_name: $NAME-zookeeper
    restart: unless-stopped
    ports:
      - $ZK_PORT:2181
    volumes:
      - zookeeper_data:/bitnami
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  cmak:
    image: ghcr.io/eshepelyuk/dckr/cmak-3.0.0.5:$CMAK_VERSION
    container_name: $NAME-cmak
    restart: unless-stopped
    ports:
      - $CMAK_PORT:9000
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: random-secret
      KAFKA_MANAGER_AUTH_ENABLED: true
      KAFKA_MANAGER_USERNAME: $CMAK_USER
      KAFKA_MANAGER_PASSWORD: $CMAK_PASSWORD
    depends_on:
      - kafka
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
